[versions]
accompanistPagerIndicators = "0.28.0"
accompanistPagerVersion = "0.28.0"
activityComposeVersion = "1.8.0"
agp = "8.13.2"

androidxActivityCompose = "1.10.1"
androidxComposeBom = "2025.03.01"
androidxComposeBomVersion = "2023.10.01"
androidxJunitVersion = "1.1.5"
androidxMaterial3 = "1.3.1"
coilCompose = "2.6.0"
coilComposeVersion = "2.4.0"
compiler = "1.5.15"
composeBomVersion = "2025.03.00"
converterGson = "2.9.0"
coreKtxVersion = "1.9.0"
espressoCoreVersion = "3.5.1"
foundation = "1.7.8"
foundationVersion = "1.5.1"
jsoup = "1.15.3"
jsoupVersion = "1.15.3"
kotlin = "1.9.0"
coreKtx = "1.15.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
kotlinxDatetime = "0.4.1"
kotlinxSerializationJson = "1.8.0"
kotlinxSerializationJsonVersion = "1.5.1"
ktorClientAndroid = "2.3.7"
ktorClientContentNegotiation = "2.3.7"
ktorSerializationKotlinxJson = "3.1.1"
ktorClientLogging = "2.3.7"
ktorSerializationKotlinxJsonVersion = "2.3.7"
lifecycleRuntimeCompose = "2.8.7"
lifecycleRuntimeKtx = "2.8.7"
activityCompose = "1.10.0"
composeBom = "2025.02.00"
lifecycleRuntimeKtxVersion = "2.6.1"
lifecycleViewmodelCompose = "2.8.7"
lifecycleViewmodelComposeVersion = "2.6.1"
loggingInterceptor = "4.9.1"
material3 = "3"
material = "1.12.0"

accompanistPager = "0.19.0"
material3Version = "1.3.1"
materialVersion = "1.7.8"
squareupRetrofitVersion = "2.9.0"
ui = "1.7.6"
material3Android = "1.3.1"
navigationRuntimeKtx = "2.8.7"
navigationCompose = "2.8.7"
navigationRuntimeAndroid = "2.9.0-alpha09"
navigationComposeVersion = "2.8.9"
playServicesBasement = "18.10.0"
animationCoreLint = "1.10.2"

[libraries]
accompanist-pager = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanistPager" }
accompanist-pager-indicators = { module = "com.google.accompanist:accompanist-pager-indicators", version.ref = "accompanistPager" }
accompanist-pager-indicators-v0280 = { module = "com.google.accompanist:accompanist-pager-indicators", version.ref = "accompanistPagerIndicators" }
accompanist-pager-v0280 = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanistPagerVersion" }
androidx-activity-compose-v1101 = { module = "androidx.activity:activity-compose", version.ref = "androidxActivityCompose" }
androidx-activity-compose-v180 = { module = "androidx.activity:activity-compose", version.ref = "activityComposeVersion" }
androidx-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "compiler" }
androidx-compose-bom-v20231001 = { module = "androidx.compose:compose-bom", version.ref = "androidxComposeBomVersion" }
androidx-compose-bom-v20250301 = { module = "androidx.compose:compose-bom", version.ref = "androidxComposeBom" }
androidx-compose-material3-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-bom-v20250300 = { module = "androidx.compose:compose-bom", version.ref = "composeBomVersion" }
androidx-compose-ui-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
androidx-compose-ui-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-compose-ui-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-compose-ui-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }

androidx-core-ktx-v1120 = { module = "androidx.core:core-ktx", version.ref = "coreKtxVersion" }
androidx-espresso-core-v351 = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCoreVersion" }
androidx-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "foundation" }
androidx-foundation-v151 = { module = "androidx.compose.foundation:foundation", version.ref = "foundationVersion" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycleRuntimeCompose" }
androidx-lifecycle-runtime-ktx-v261 = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtxVersion" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelCompose" }
androidx-lifecycle-viewmodel-compose-v261 = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelComposeVersion" }
androidx-material = { module = "androidx.compose.material:material", version.ref = "materialVersion" }
androidx-material3-v101 = { module = "androidx.compose.material3:material3", version.ref = "androidxMaterial3" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }
coil-compose-v240 = { module = "io.coil-kt:coil-compose", version.ref = "coilComposeVersion" }
com-squareup-retrofit2-retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "squareupRetrofitVersion" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
jsoup-v1153 = { module = "org.jsoup:jsoup", version.ref = "jsoupVersion" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
junit-v115 = { module = "androidx.test.ext:junit", version.ref = "androidxJunitVersion" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
kotlinx-serialization-json-v151 = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJsonVersion" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktorClientContentNegotiation" }
ktor-client-android = { module = "io.ktor:ktor-client-android", version.ref = "ktorClientAndroid" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktorClientLogging" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktorSerializationKotlinxJson" }
ktor-serialization-kotlinx-json-v237 = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktorSerializationKotlinxJsonVersion" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
material = { module = "com.google.android.material:material", version.ref = "material" }
androidx-navigation-runtime-ktx = { group = "androidx.navigation", name = "navigation-runtime-ktx", version.ref = "navigationRuntimeKtx" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
material3 = { module = "androidx.compose.material3:material3", version.ref = "material3Version" }
ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
ui = { module = "androidx.compose.ui:ui" }
androidx-navigation-runtime-android = { group = "androidx.navigation", name = "navigation-runtime-android", version.ref = "navigationRuntimeAndroid" }
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationComposeVersion" }
play-services-basement = { group = "com.google.android.gms", name = "play-services-basement", version.ref = "playServicesBasement" }
androidx-compose-animation-core-lint = { group = "androidx.compose.animation", name = "animation-core-lint", version.ref = "animationCoreLint" }
[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
